# Render deployment configuration
services:
  # Backend API service
  - type: web
    name: idea-hub-backend
    runtime: node
    plan: starter
    buildCommand: yarn && yarn workspace @idea-hub/shared build && yarn workspace @idea-hub/backend add -D @types/express @types/cors @types/uuid && yarn workspace @idea-hub/backend build:deploy
    startCommand: cd services/backend && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: idea-hub-db
          property: connectionString
      # Explicit database connection variables as fallback
      - key: RENDER_DB_SERVICE_HOSTNAME
        value: dpg-cvb1tq2j1k6c7392iva0-a
      - key: RENDER_DB_SERVICE_PORT
        value: 5432
      - key: RENDER_DB_SERVICE_USER
        value: idea_hub_db_user
      - key: RENDER_DB_SERVICE_PASSWORD
        sync: false # Will prompt during deployment
      - key: RENDER_DB_SERVICE_DATABASE
        value: idea_hub_db
      - key: RENDER_DB_SERVICE_INTERNAL_DB_URL
        value: postgresql://idea_hub_db_user:${RENDER_DB_SERVICE_PASSWORD}@dpg-cvb1tq2j1k6c7392iva0-a/idea_hub_db
      - key: AI_SERVICE_URL
        value: https://idea-hub-ai-service.onrender.com
      - key: CLERK_SECRET_KEY
        sync: false # This tells Render to prompt for the value during deployment

  # Web app service
  - type: web
    name: idea-hub-web
    runtime: node
    plan: starter
    buildCommand: yarn && cd apps/web && yarn add -D vite@5.0.5 @vitejs/plugin-react@4.2.1 @tailwindcss/postcss@4.0.14 tailwindcss@4.0.14 postcss@8.5.3 autoprefixer@10.4.21 && yarn build:skipTypeCheck
    startCommand: cd apps/web && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: BACKEND_URL
        value: https://idea-hub-backend.onrender.com
      - key: VITE_CLERK_PUBLISHABLE_KEY
        value: pk_test_bWFnaWNhbC13ZWFzZWwtNDQuY2xlcmsuYWNjb3VudHMuZGV2JA

  # AI Service (Python + FastAPI)
  - type: web
    name: idea-hub-ai-service
    runtime: python
    plan: starter
    buildCommand: cd services/ai && pip install -r requirements.txt
    startCommand: cd services/ai && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: MILVUS_URL
        value: https://idea-hub-milvus-proxy.onrender.com

  # Background worker for compute-intensive tasks
  - type: worker
    name: idea-hub-worker
    runtime: node
    plan: starter
    buildCommand: yarn && yarn workspace @idea-hub/shared build
    startCommand: cd services/backend && node worker.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: idea-hub-db
          property: connectionString
      # Explicit database connection variables as fallback
      - key: RENDER_DB_SERVICE_HOSTNAME
        value: dpg-cvb1tq2j1k6c7392iva0-a
      - key: RENDER_DB_SERVICE_PORT
        value: 5432
      - key: RENDER_DB_SERVICE_USER
        value: idea_hub_db_user
      - key: RENDER_DB_SERVICE_PASSWORD
        sync: false # Will prompt during deployment
      - key: RENDER_DB_SERVICE_DATABASE
        value: idea_hub_db
      - key: RENDER_DB_SERVICE_INTERNAL_DB_URL
        value: postgresql://idea_hub_db_user:${RENDER_DB_SERVICE_PASSWORD}@dpg-cvb1tq2j1k6c7392iva0-a/idea_hub_db
      - key: AI_SERVICE_URL
        value: https://idea-hub-ai-service.onrender.com
      - key: CLERK_SECRET_KEY
        sync: false # This tells Render to prompt for the value during deployment

# Database
databases:
  - name: idea-hub-db
    plan: basic-256mb
    ipAllowList: [] # Only allow internal connections 